---
- name: KÃ¸r kommandoen id
  hosts: all
  gather_facts: yes

  tasks:
    - name: Vis bruger-id
      command: id
      register: id_output

    - name: Print output
      debug:
        var: id_output.stdout

